version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - git submodule update --init --recursive
    post_install:
      - cp -a locales foamlib/docs/

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: foamlib/docs/conf.py
  fail_on_warning: false
  builder: html
